"@jsxcss/core":
  - packages/core/*
  - packages/core/**/*
"@jsxcss/emotion":
  - packages/emotion/*
  - packages/emotion/**/*
"@jsxcss/devtool":
  - packages/devtool/*
  - packages/devtool/**/*
websites/docs:
  - websites/docs/*
  - websites/docs/**/*
websites/emotion:
  - websites/emotion/*
  - websites/emotion/**/*
babel:
  - configs/babel/*
  - configs/babel/**/*
eslint:
  - configs/eslint/*
  - configs/eslint/**/*
rollup:
  - configs/rollup/*
  - configs/rollup/**/*
tsconfig:
  - configs/tsconfig/*
  - configs/tsconfig/**/*
configuration:
  - next.config.js
  - package*.json
  - "**/.*"
  - "**/tsconfig*.json"
  - .*/**
documentation:
  - "**/*.md"
dependencies:
  - "**/pnpm-lock.yaml"
workflows:
  - .github/*
  - .github/**/*
